create sequence student_sequence start with 1 increment by 1;

CREATE TABLE student (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null
);

insert into student (id, name) values (1, 'maria');
insert into student (id, name) values (2, 'Antonio');
insert into student (id, name) values (3, 'Ze');